# Generated by Django 4.1.2 on 2023-03-22 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Person",
            new_name="PersonList",
        ),
    ]
