# Generated by Django 4.2.2 on 2023-12-01 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0005_contact_yourmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Memory',
        ),
        migrations.DeleteModel(
            name='YourModel',
        ),
    ]
