# Generated by Django 4.2.2 on 2023-12-02 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0006_diaryitem_delete_contact_delete_memory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('username', models.CharField(max_length=150)),
                ('birthday', models.DateField()),
            ],
        ),
    ]
